services:
  db: 
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - "./data/pg-data:/var/lib/postgresql/data:rw"
    restart: unless-stopped